
def generate_dates(start_year, end_year):
    result = []
    months = [("12", "31"), ("09", "30"), ("06", "30"), ("03", "31")]

    for year in range(start_year, end_year - 1, -1):
        for month, day in months:
            result.append(f"{year}-{month}-{day}")

    return result

# dates = generate_dates(2026, 2003)
# for date in dates:
#     print(date)

QUARTER_DATES=[
    "2025-12-31",
    "2025-09-30",
    "2025-06-30",
    "2025-03-31",
    "2024-12-31",
    "2024-09-30",
    "2024-06-30",
    "2024-03-31",
    "2023-12-31",
    "2023-09-30",
    "2023-06-30",
    "2023-03-31",
    "2022-12-31",
    "2022-09-30",
    "2022-06-30",
    "2022-03-31",
    "2021-12-31",
    "2021-09-30",
    "2021-06-30",
    "2021-03-31",
    "2020-12-31",
    "2020-09-30",
    "2020-06-30",
    "2020-03-31",
    "2019-12-31",
    "2019-09-30",
    "2019-06-30",
    "2019-03-31",
    "2018-12-31",
    "2018-09-30",
    "2018-06-30",
    "2018-03-31",
    "2017-12-31",
    "2017-09-30",
    "2017-06-30",
    "2017-03-31",
    "2016-12-31",
    "2016-09-30",
    "2016-06-30",
    "2016-03-31",
    "2015-12-31",
    "2015-09-30",
    "2015-06-30",
    "2015-03-31",
    "2014-12-31",
    "2014-09-30",
    "2014-06-30",
    "2014-03-31",
    "2013-12-31",
    "2013-09-30",
    "2013-06-30",
    "2013-03-31",
    "2012-12-31",
    "2012-09-30",
    "2012-06-30",
    "2012-03-31",
    "2011-12-31",
    "2011-09-30",
    "2011-06-30",
    "2011-03-31",
    "2010-12-31",
    "2010-09-30",
    "2010-06-30",
    "2010-03-31",
    "2009-12-31",
    "2009-09-30",
    "2009-06-30",
    "2009-03-31",
    "2008-12-31",
    "2008-09-30",
    "2008-06-30",
    "2008-03-31",
    "2007-12-31",
    "2007-09-30",
    "2007-06-30",
    "2007-03-31",
    "2006-12-31",
    "2006-09-30",
    "2006-06-30",
    "2006-03-31",
    "2005-12-31",
    "2005-09-30",
    "2005-06-30",
    "2005-03-31",
    "2004-12-31",
    "2004-09-30",
    "2004-06-30",
    "2004-03-31",
    "2003-12-31",
    "2003-09-30",
    "2003-06-30",
    "2003-03-31"
]





BANK_INFO = {
    "000001.SZ": {"shortName": "PING AN BANK", "currency": "CNY" },
    "0011.HK": {"shortName": "HANG SENG BANK", "currency": "HKD" },
    "002142.SZ": {"shortName": "BANK OF NINGBO CO.", "currency": "CNY" },
    "0023.HK": {"shortName": "BANK OF E ASIA", "currency": "HKD" },
    "0440.HK": {"shortName": "DAH SING", "currency": "HKD" },
    "0B2.F": {"shortName": "BAWAG GROUP AG", "currency": "EUR" },
    "1010.SR": {"shortName": "Riyad Bank", "currency": "SAR" },
    "1020.SR": {"shortName": "Bank Aljazira", "currency": "SAR" },
    "1023.KL": {"shortName": "CIMB", "currency": "MYR" },
    "1030.SR": {"shortName": "Saudi Investment Bank", "currency": "SAR" },
    "1050.SR": {"shortName": "Banque Saudi Fransi", "currency": "SAR" },
    "1060.SR": {"shortName": "Saudi Awwal Bank", "currency": "SAR" },
    "1080.SR": {"shortName": "Arab National Bank", "currency": "SAR" },
    "1120.SR": {"shortName": "Al Rajhi Bank", "currency": "SAR" },
    "1140.SR": {"shortName": "Bank Albilad", "currency": "SAR" },
    "1150.SR": {"shortName": "Alinma Bank", "currency": "SAR" },
    "1180.SR": {"shortName": "The Saudi National Bank", "currency": "SAR" },
    "1295.KL": {"shortName": "PBBANK", "currency": "MYR" },
    "1398.HK": {"shortName": "ICBC", "currency": "HKD" },
    "2016.HK": {"shortName": "CZBANK", "currency": "HKD" },
    "2356.HK": {"shortName": "DAHSING BANKING", "currency": "HKD" },
    "2388.HK": {"shortName": "BOC HONG KONG", "currency": "HKD" },
    "2801.TW": {"shortName": "CHANG HWA COMMERCIAL BANK LTD", "currency": "TWD" },
    "2834.TW": {"shortName": "TAIWAN BUSINESS BANK", "currency": "TWD" },
    "2880.TW": {"shortName": "HUA NAN FINANCIAL HOLDINGS CO", "currency": "TWD" },
    "2881.TW": {"shortName": "FUBON FINANCIAL HLDG CO LTD", "currency": "TWD" },
    "2882.TW": {"shortName": "CATHAY FINANCIAL HLDG CO", "currency": "TWD" },
    "2883.TW": {"shortName": "CHINA DEVELOPMENT FINANCIAL HLD", "currency": "TWD" },
    "2884.TW": {"shortName": "E SUN FINANCIAL HOLDINGS", "currency": "TWD" },
    "2885.TW": {"shortName": "YUANTA FINANCIAL HOLDING CO. LT", "currency": "TWD" },
    "2886.TW": {"shortName": "MEGA FINANCIAL HOLDING CO", "currency": "TWD" },
    "2887.TW": {"shortName": "TAISHIN FINANCIAL HLDGS CO LTD", "currency": "TWD" },
    "2888.TW": {"shortName": "SHIN KONG FINANCIAL HLDG CO", "currency": "TWD" },
    "2890.TW": {"shortName": "SINOPAC FINANCIAL HLDGS CO LTD", "currency": "TWD" },
    "2891.TW": {"shortName": "CTBC FINANCIAL HOLDINGS COMPANY", "currency": "TWD" },
    "2892.TW": {"shortName": "FIRST FINANCIAL HOLDING CO LTD", "currency": "TWD" },
    "3618.HK": {"shortName": "CQRC BANK", "currency": "HKD" },
    "3968.HK": {"shortName": "CM BANK", "currency": "HKD" },
    "5819.KL": {"shortName": "HLBANK", "currency": "MYR" },
    "5876.TW": {"shortName": "THE SHANGHAI COMM & SAVINGS BAN", "currency": "TWD" },
    "5880.TW": {"shortName": "TAIWAN COOPERATIVE FINANCIAL HL", "currency": "TWD" },
    "600000.SS": {"shortName": "SHANGHAI PUDONG DEVELOPMENT BAN", "currency": "CNY" },
    "600015.SS": {"shortName": "HUAXIA BANK CO", "currency": "CNY" },
    "600016.SS": {"shortName": "CHINA MINSHENG BANKING CORP", "currency": "CNY" },
    "600030.SS": {"shortName": "CITIC SECURITIES CO LTD", "currency": "CNY" },
    "600919.SS": {"shortName": "BANK OF JIANGSU", "currency": "CNY" },
    "601009.SS": {"shortName": "BANK OF NANJING CO. LTD.", "currency": "CNY" },
    "601166.SS": {"shortName": "INDUSTRIAL BANK CO LTD", "currency": "CNY" },
    "601169.SS": {"shortName": "BANK OF BEIJING CO. LTD.", "currency": "CNY" },
    "601211.SS": {"shortName": "GUOTAI JUNAN SECURITIES CO LTD", "currency": "CNY" },
    "601229.SS": {"shortName": "BANK OF SHANGHAI CO LTD", "currency": "CNY" },
    "601288.SS": {"shortName": "AGRICULTURAL BANK OF CHINA", "currency": "CNY" },
    "601328.SS": {"shortName": "BANK OF COMMUNICATIONS CO LTD", "currency": "CNY" },
    "601658.SS": {"shortName": "POSTAL SAVINGS BANK OF CHINA CO", "currency": "CNY" },
    "601818.SS": {"shortName": "CHINA EVERBRIGHT BANK CO LTD", "currency": "CNY" },
    "601939.SS": {"shortName": "CHINA CONSTRUCTION BANK", "currency": "CNY" },
    "601988.SS": {"shortName": "BANK OF CHINA LTD", "currency": "CNY" },
    "601998.SS": {"shortName": "CHINA CITIC BANK CORPORATION LT", "currency": "CNY" },
    "7182.T": {"shortName": "JAPAN POST BANK CO LTD", "currency": "JPY" },
    "8308.T": {"shortName": "RESONA HOLDINGS", "currency": "JPY" },
    "8421.T": {"shortName": "SHINKIN CENTRAL BANK NON-CUM PR", "currency": "JPY" },
    "8601.T": {"shortName": "DAIWA SECURITIES GROUP", "currency": "JPY" },
    "A5G.IR": {"shortName": "AIB GROUP PLC", "currency": "EUR" },
    "ABN.AS": {"shortName": "ABN AMRO BANK N.V.", "currency": "EUR" },
    "ACA.PA": {"shortName": "CREDIT AGRICOLE", "currency": "EUR" },
    "ACNB": {"shortName": "ACNB Corporation", "currency": "USD" },
    "AKBNK.IS": {"shortName": "AKBANK", "currency": "TRY" },
    "AKTIA.HE": {"shortName": "Aktia Bank Plc", "currency": "EUR" },
    "ALLY": {"shortName": "Ally Financial Inc.", "currency": "USD" },
    "ALPHA.AT": {"shortName": "ALPHA SERVICES AND HOLDINGS SA", "currency": "EUR" },
    "ALRS": {"shortName": "Alerus Financial Corporation", "currency": "USD" },
    "AMAL": {"shortName": "Amalgamated Financial Corp.", "currency": "USD" },
    "AMNB": {"shortName": "American National Bankshares, I", "currency": "USD" },
    "AMTB": {"shortName": "Amerant Bancorp Inc.", "currency": "USD" },
    "ANZ.AX": {"shortName": "ANZ GROUP FPO", "currency": "AUD" },
    "ARION.IC": {"shortName": "Arion banki hf.", "currency": "ISK" },
    "ARL.F": {"shortName": "AAREAL BANK AG", "currency": "EUR" },
    "AROW": {"shortName": "Arrow Financial Corporation", "currency": "USD" },
    "ARTO.JK": {"shortName": "Bank Jago Tbk.", "currency": "IDR" },
    "ASB": {"shortName": "Associated Banc-Corp", "currency": "USD" },
    "ATLO": {"shortName": "Ames National Corporation", "currency": "USD" },
    "AUB": {"shortName": "Atlantic Union Bankshares Corpo", "currency": "USD" },
    "AUBANK.NS": {"shortName": "AU SMALL FINANCE B", "currency": "INR" },
    "AX": {"shortName": "Axos Financial, Inc.", "currency": "USD" },
    "AXISBANK.BO": {"shortName": "AXIS BANK LTD.", "currency": "INR" },
    "BAC": {"shortName": "Bank of America Corporation", "currency": "USD" },
    "BAER.SW": {"shortName": "JULIUS BAER N", "currency": "CHF" },
    "BAMI.MI": {"shortName": "BANCO BPM", "currency": "EUR" },
    "BANC": {"shortName": "Banc of California, Inc.", "currency": "USD" },
    "BANDHANBNK.NS": {"shortName": "BANDHAN BANK LTD", "currency": "INR" },
    "BANF": {"shortName": "BancFirst Corporation", "currency": "USD" },
    "BANKBARODA.NS": {"shortName": "BK OF BARODA", "currency": "INR" },
    "BANKINDIA.NS": {"shortName": "BK OF INDIA", "currency": "INR" },
    "BANR": {"shortName": "Banner Corporation", "currency": "USD" },
    "BAP": {"shortName": "Credicorp Ltd.", "currency": "USD" },
    "BBAJIOO.MX": {"shortName": "BANCO DEL BAJIO", "currency": "MXN" },
    "BBAR": {"shortName": "Banco BBVA Argentina S.A.", "currency": "USD" },
    "BBAS3.SA": {"shortName": "BRASIL      ON      NM", "currency": "BRL" },
    "BBCA.JK": {"shortName": "Bank Central Asia Tbk", "currency": "IDR" },
    "BBD": {"shortName": "Banco Bradesco Sa", "currency": "USD" },
    "BBL.BK": {"shortName": "BBL_BANGKOK BANK", "currency": "THB" },
    "BBNI.JK": {"shortName": "Bank Negara Indonesia  (Persero", "currency": "IDR" },
    "BBRI.JK": {"shortName": "Bank Rakyat Indonesia (Persero)", "currency": "IDR" },
    "BBVA": {"shortName": "Banco Bilbao Vizcaya Argentaria", "currency": "USD" },
    "BCBP": {"shortName": "BCB Bancorp, Inc. (NJ)", "currency": "USD" },
    "BCH": {"shortName": "Banco De Chile Banco De Chile", "currency": "USD" },
    "BCI.SN": {"shortName": "BANCO DE CREDITO E INVERSIONES", "currency": "CLP" },
    "BCML": {"shortName": "BayCom Corp", "currency": "USD" },
    "BCP.LS": {"shortName": "B.C.P.-BCO COMERCIAL PORTUGUES", "currency": "EUR" },
    "BCS": {"shortName": "Barclays PLC", "currency": "USD" },
    "BCVN.SW": {"shortName": "BC VAUD N", "currency": "CHF" },
    "BDMN.JK": {"shortName": "Bank Danamon Indonesia Tbk.", "currency": "IDR" },
    "BDOUY": {"shortName": "BDO UNIBANK INC SPON ADR EA REP", "currency": "USD" },
    "BEKN.SW": {"shortName": "BEKB / BCBE N", "currency": "CHF" },
    "BEN.AX": {"shortName": "BEN ADE BK FPO", "currency": "AUD" },
    "BFC": {"shortName": "Bank First Corporation", "currency": "USD" },
    "BFIN": {"shortName": "BankFinancial Corporation", "currency": "USD" },
    "BHB": {"shortName": "Bar Harbor Bankshares, Inc.", "currency": "USD" },
    "BHLB": {"shortName": "Berkshire Hills Bancorp, Inc.", "currency": "USD" },
    "BIRG.IR": {"shortName": "BANK OF IRELAND GROUP PLC", "currency": "EUR" },
    "BK": {"shortName": "The Bank of New York Mellon Cor", "currency": "USD" },
    "BKT.MC": {"shortName": "BANKINTER, S.A.", "currency": "EUR" },
    "BKU": {"shortName": "BankUnited, Inc.", "currency": "USD" },
    "BLX": {"shortName": "Banco Latinoamericano de Comerc", "currency": "USD" },
    "BMA": {"shortName": "Banco Macro S.A.", "currency": "USD" },
    "BMED.MI": {"shortName": "BANCA MEDIOLANUM", "currency": "EUR" },
    "BMO": {"shortName": "Bank Of Montreal", "currency": "USD" },
    "BMRC": {"shortName": "Bank of Marin Bancorp", "currency": "USD" },
    "BMRI.JK": {"shortName": "Bank Mandiri (Persero) Tbk", "currency": "IDR" },
    "BNLI.JK": {"shortName": "Bank Permata Tbk", "currency": "IDR" },
    "BNP.PA": {"shortName": "BNP PARIBAS ACT.A", "currency": "EUR" },
    "BNS": {"shortName": "Bank Nova Scotia Halifax Pfd 3", "currency": "USD" },
    "BOH": {"shortName": "Bank of Hawaii Corporation", "currency": "USD" },
    "BOKF": {"shortName": "BOK Financial Corporation", "currency": "USD" },
    "BPOP": {"shortName": "Popular, Inc.", "currency": "USD" },
    "BRKL": {"shortName": "Brookline Bancorp, Inc.", "currency": "USD" },
    "BSAC": {"shortName": "Banco Santander - Chile", "currency": "USD" },
    "BSBR": {"shortName": "Banco Santander Brasil SA", "currency": "USD" },
    "BSLI3.SA": {"shortName": "BRB BANCO   ON", "currency": "BRL" },
    "BSRR": {"shortName": "Sierra Bancorp", "currency": "USD" },
    "BSVN": {"shortName": "Bank7 Corp.", "currency": "USD" },
    "BTS.VI": {"shortName": "Bank fuer Tirol und Vbg AG", "currency": "EUR" },
    "BUSE": {"shortName": "First Busey Corporation", "currency": "USD" },
    "BWB": {"shortName": "Bridgewater Bancshares, Inc.", "currency": "USD" },
    "BWFG": {"shortName": "Bankwell Financial Group, Inc.", "currency": "USD" },
    "BY": {"shortName": "Byline Bancorp, Inc.", "currency": "USD" },
    "C": {"shortName": "Citigroup, Inc.", "currency": "USD" },
    "CABK.MC": {"shortName": "CAIXABANK, S.A.", "currency": "EUR" },
    "CAC": {"shortName": "Camden National Corporation", "currency": "USD" },
    "CADE": {"shortName": "Cadence Bank", "currency": "USD" },
    "CALB": {"shortName": "California BanCorp", "currency": "USD" },
    "CANBK.NS": {"shortName": "CANARA BANK", "currency": "INR" },
    "CARV": {"shortName": "Carver Bancorp, Inc.", "currency": "USD" },
    "CASH": {"shortName": "Pathward Financial, Inc.", "currency": "USD" },
    "CATC": {"shortName": "Cambridge Bancorp", "currency": "USD" },
    "CATY": {"shortName": "Cathay General Bancorp", "currency": "USD" },
    "CBA.AX": {"shortName": "CWLTH BANK FPO", "currency": "AUD" },
    "CBG.L": {"shortName": "CLOSE BROTHERS GROUP PLC ORD 25", "currency": "GBP" },
    "CBK.F": {"shortName": "COMMERZBANK AG", "currency": "EUR" },
    "CBSH": {"shortName": "Commerce Bancshares, Inc.", "currency": "USD" },
    "CBU": {"shortName": "Community Bank System, Inc.", "currency": "USD" },
    "CCBG": {"shortName": "Capital City Bank Group", "currency": "USD" },
    "CCNE": {"shortName": "CNB Financial Corporation", "currency": "USD" },
    "CFFI": {"shortName": "C&F Financial Corporation", "currency": "USD" },
    "CFFN": {"shortName": "Capitol Federal Financial, Inc.", "currency": "USD" },
    "CFG": {"shortName": "Citizens Financial Group, Inc.", "currency": "USD" },
    "CFR": {"shortName": "Cullen/Frost Bankers, Inc.", "currency": "USD" },
    "CHBAY": {"shortName": "CHIBA BANK UNSP ADR EACH REPR 5", "currency": "USD" },
    "CHCO": {"shortName": "City Holding Company", "currency": "USD" },
    "CIB": {"shortName": "BanColombia S.A.", "currency": "USD" },
    "CIN.F": {"shortName": "COM.INTL BK GDR S LE 10", "currency": "EUR" },
    "CIVB": {"shortName": "Civista Bancshares, Inc.", "currency": "USD" },
    "CM": {"shortName": "Canadian Imperial Bank of Comme", "currency": "USD" },
    "CMBN.SW": {"shortName": "CEMBRA MONEY BANK N", "currency": "CHF" },
    "CNOB": {"shortName": "ConnectOne Bancorp, Inc.", "currency": "USD" },
    "COF": {"shortName": "Capital One Financial Corporati", "currency": "USD" },
    "COLB": {"shortName": "Columbia Banking System, Inc.", "currency": "USD" },
    "CPF": {"shortName": "Central Pacific Financial Corp ", "currency": "USD" },
    "CPI.JO": {"shortName": "Capitec Bank Hldgs Ltd", "currency": "ZAR" },
    "CS": {"shortName": "Credit Suisse Group", "currency": "USD" },
    "CSBBANK.NS": {"shortName": "CSB Bank Limited", "currency": "INR" },
    "CSTR": {"shortName": "CapStar Financial Holdings, Inc", "currency": "USD" },
    "CTBI": {"shortName": "Community Trust Bancorp, Inc.", "currency": "USD" },
    "CUB.NS": {"shortName": "CITY UNION BANK", "currency": "INR" },
    "CUBI": {"shortName": "Customers Bancorp, Inc", "currency": "USD" },
    "CVBF": {"shortName": "CVB Financial Corporation", "currency": "USD" },
    "CVCY": {"shortName": "Central Valley Community Bancor", "currency": "USD" },
    "CVLY": {"shortName": "Codorus Valley Bancorp, Inc", "currency": "USD" },
    "CWB.TO": {"shortName": "CDN WESTERN BANK", "currency": "CAD" },
    "CZNC": {"shortName": "Citizens & Northern Corp", "currency": "USD" },
    "D05.SI": {"shortName": "DBS", "currency": "SGD" },
    "DANS.VI": {"shortName": "DANSKE BANK AS", "currency": "EUR" },
    "DB": {"shortName": "Deutsche Bank AG", "currency": "USD" },
    "DCOM": {"shortName": "Dime Community Bancshares, Inc.", "currency": "USD" },
    "DSY.JO": {"shortName": "Discovery Ltd", "currency": "ZAR" },
    "EBC": {"shortName": "Eastern Bankshares, Inc.", "currency": "USD" },
    "EBO.F": {"shortName": "ERSTE GROUP BNK INH. O.N.", "currency": "EUR" },
    "EBTC": {"shortName": "Enterprise Bancorp Inc", "currency": "USD" },
    "ECBK": {"shortName": "ECB Bancorp, Inc.", "currency": "USD" },
    "EFGN.SW": {"shortName": "EFG INTERNATIONAL N", "currency": "CHF" },
    "EFSC": {"shortName": "Enterprise Financial Services C", "currency": "USD" },
    "EGBN": {"shortName": "Eagle Bancorp, Inc.", "currency": "USD" },
    "EQB.TO": {"shortName": "EQB INC", "currency": "CAD" },
    "EQBK": {"shortName": "Equity Bancshares, Inc.", "currency": "USD" },
    "ESSA": {"shortName": "ESSA Bancorp, Inc.", "currency": "USD" },
    "ETE.AT": {"shortName": "National Bank of Greece (CR)", "currency": "EUR" },
    "EUROB.AT": {"shortName": "EUROBANK HOLDINGS (CR)", "currency": "EUR" },
    "EVBN": {"shortName": "Evans Bancorp, Inc.", "currency": "USD" },
    "EWBC": {"shortName": "East West Bancorp, Inc.", "currency": "USD" },
    "FBIZ": {"shortName": "First Business Financial Servic", "currency": "USD" },
    "FBK": {"shortName": "FB Financial Corporation", "currency": "USD" },
    "FBMS": {"shortName": "The First Bancshares, Inc.", "currency": "USD" },
    "FBNC": {"shortName": "First Bancorp", "currency": "USD" },
    "FCF": {"shortName": "First", "currency": "USD" },
    "FCNCA": {"shortName": "First Citizens BancShares, Inc.", "currency": "USD" },
    "FEDERALBNK.NS": {"shortName": "FED BANK", "currency": "INR" },
    "FFBC": {"shortName": "First Financial Bancorp.", "currency": "USD" },
    "FFIC": {"shortName": "Flushing Financial Corporation", "currency": "USD" },
    "FFIN": {"shortName": "First Financial Bankshares, Inc", "currency": "USD" },
    "FFWM": {"shortName": "First Foundation Inc.", "currency": "USD" },
    "FGBI": {"shortName": "First Guaranty Bancshares, Inc.", "currency": "USD" },
    "FHB": {"shortName": "First Hawaiian, Inc.", "currency": "USD" },
    "FHN": {"shortName": "First Horizon Corporation", "currency": "USD" },
    "FIBI.TA": {"shortName": "FIBI BANK", "currency": "ILS" },
    "FIBK": {"shortName": "First Interstate BancSystem, In", "currency": "USD" },
    "FINN": {"shortName": "FIRST NATIONAL OF NEBRASKA INC", "currency": "USD" },
    "FINW": {"shortName": "FinWise Bancorp", "currency": "USD" },
    "FISI": {"shortName": "Financial Institutions, Inc.", "currency": "USD" },
    "FITB": {"shortName": "Fifth Third Bancorp", "currency": "USD" },
    "FMAO": {"shortName": "Farmers & Merchants Bancorp, In", "currency": "USD" },
    "FMBH": {"shortName": "First Mid Bancshares, Inc.", "currency": "USD" },
    "FNB": {"shortName": "F.N.B. Corporation", "currency": "USD" },
    "FNLC": {"shortName": "First Bancorp, Inc (ME)", "currency": "USD" },
    "FNWB": {"shortName": "First Northwest Bancorp", "currency": "USD" },
    "FRBK": {"shortName": "Republic First Bancorp, Inc.", "currency": "USD" },
    "FRCB": {"shortName": "FIRST REPUBLIC BANK", "currency": "USD" },
    "FRME": {"shortName": "First Merchants Corporation", "currency": "USD" },
    "FSBC": {"shortName": "Five Star Bancorp", "currency": "USD" },
    "FSR.JO": {"shortName": "Firstrand Ltd", "currency": "ZAR" },
    "FULT": {"shortName": "Fulton Financial Corporation", "currency": "USD" },
    "GABC": {"shortName": "German American Bancorp, Inc.", "currency": "USD" },
    "GARAN.IS": {"shortName": "GARANTI BANKASI", "currency": "TRY" },
    "GBCI": {"shortName": "Glacier Bancorp, Inc.", "currency": "USD" },
    "GCBC": {"shortName": "Greene County Bancorp, Inc.", "currency": "USD" },
    "GGAL": {"shortName": "Grupo Financiero Galicia S.A.", "currency": "USD" },
    "GHL": {"shortName": "Greenhill & Co., Inc.", "currency": "USD" },
    "GLE.PA": {"shortName": "SOCIETE GENERALE", "currency": "EUR" },
    "GNTY": {"shortName": "Guaranty Bancshares, Inc.", "currency": "USD" },
    "GS": {"shortName": "Goldman Sachs Group, Inc. (The)", "currency": "USD" },
    "GSBC": {"shortName": "Great Southern Bancorp, Inc.", "currency": "USD" },
    "HAFC": {"shortName": "Hanmi Financial Corporation", "currency": "USD" },
    "HALKB.IS": {"shortName": "T. HALK BANKASI", "currency": "TRY" },
    "HBAN": {"shortName": "Huntington Bancshares Incorpora", "currency": "USD" },
    "HBCP": {"shortName": "Home Bancorp, Inc.", "currency": "USD" },
    "HBNC": {"shortName": "Horizon Bancorp, Inc.", "currency": "USD" },
    "HBT": {"shortName": "HBT Financial, Inc.", "currency": "USD" },
    "HDB": {"shortName": "HDFC Bank Limited", "currency": "USD" },
    "HDFC.NS": {"shortName": "HOUSING DEVEL FIN", "currency": "INR" },
    "HFWA": {"shortName": "Heritage Financial Corporation", "currency": "USD" },
    "HIFS": {"shortName": "Hingham Institution for Savings", "currency": "USD" },
    "HMST": {"shortName": "HomeStreet, Inc.", "currency": "USD" },
    "HNVR": {"shortName": "Hanover Bancorp, Inc.", "currency": "USD" },
    "HONE": {"shortName": "HarborOne Bancorp, Inc.", "currency": "USD" },
    "HOPE": {"shortName": "Hope Bancorp, Inc.", "currency": "USD" },
    "HSBC": {"shortName": "HSBC Holdings, plc.", "currency": "USD" },
    "HTBI": {"shortName": "HomeTrust Bancshares, Inc.", "currency": "USD" },
    "HTBK": {"shortName": "Heritage Commerce Corp", "currency": "USD" },
    "HTLF": {"shortName": "Heartland Financial USA, Inc.", "currency": "USD" },
    "HWBK": {"shortName": "Hawthorn Bancshares, Inc.", "currency": "USD" },
    "IBN": {"shortName": "ICICI Bank Limited", "currency": "USD" },
    "IBOC": {"shortName": "International Bancshares Corpor", "currency": "USD" },
    "IBTX": {"shortName": "Independent Bank Group, Inc", "currency": "USD" },
    "IDBI.NS": {"shortName": "IDBI BANK LTD", "currency": "INR" },
    "IDFCFIRSTB.NS": {"shortName": "IDFC FIRST BANK", "currency": "INR" },
    "INDB": {"shortName": "Independent Bank Corp.", "currency": "USD" },
    "INDIANB.NS": {"shortName": "INDIAN BANK", "currency": "INR" },
    "INDUSINDBK.NS": {"shortName": "INDUSIND BANK LTD", "currency": "INR" },
    "ING": {"shortName": "ING Group, N.V.", "currency": "USD" },
    "INTR": {"shortName": "Inter & Co. Inc.", "currency": "USD" },
    "IOB.NS": {"shortName": "INDIAN OVERSEAS BK", "currency": "INR" },
    "ISCTR.IS": {"shortName": "IS BANKASI (C)", "currency": "TRY" },
    "ISP.MI": {"shortName": "INTESA SANPAOLO", "currency": "EUR" },
    "ISTR": {"shortName": "Investar Holding Corporation", "currency": "USD" },
    "ITUB": {"shortName": "Itau Unibanco Banco Holding SA", "currency": "USD" },
    "IX": {"shortName": "Orix Corp", "currency": "USD" },
    "JEF": {"shortName": "Jefferies Financial Group Inc.", "currency": "USD" },
    "JPM": {"shortName": "JP Morgan Chase & Co.", "currency": "USD" },
    "JYSK.CO": {"shortName": "Jyske Bank A/S", "currency": "DKK" },
    "KARURVYSYA.NS": {"shortName": "KARUR VYSYA BANK", "currency": "INR" },
    "KB": {"shortName": "KB Financial Group Inc", "currency": "USD" },
    "KBANK.BK": {"shortName": "KBANK_KASIKORNBANK", "currency": "THB" },
    "KEY": {"shortName": "KeyCorp", "currency": "USD" },
    "KLNMA.IS": {"shortName": "T. KALKINMA BANK.", "currency": "TRY" },
    "KOMB.PR": {"shortName": "KOMERCNI BANKA", "currency": "CZK" },
    "KOTAKBANK.NS": {"shortName": "KOTAK MAHINDRA BAN", "currency": "INR" },
    "KRNY": {"shortName": "Kearny Financial", "currency": "USD" },
    "KTKBANK.NS": {"shortName": "KARNATAKA BANK", "currency": "INR" },
    "LB.TO": {"shortName": "LAURENTIAN BANK", "currency": "CAD" },
    "LBAI": {"shortName": "Lakeland Bancorp, Inc.", "currency": "USD" },
    "LBC": {"shortName": "Luther Burbank Corporation", "currency": "USD" },
    "LKFN": {"shortName": "Lakeland Financial Corporation", "currency": "USD" },
    "LOB": {"shortName": "Live Oak Bancshares, Inc.", "currency": "USD" },
    "LUKN.SW": {"shortName": "LUZERNER KB N", "currency": "CHF" },
    "LUMI.TA": {"shortName": "LEUMI", "currency": "ILS" },
    "LYG": {"shortName": "Lloyds Banking Group Plc", "currency": "USD" },
    "MAHABANK.NS": {"shortName": "BK OF MAHARASHTRA", "currency": "INR" },
    "MAYA.JK": {"shortName": "Bank Mayapada Internasional Tbk", "currency": "IDR" },
    "MB.MI": {"shortName": "MEDIOBANCA", "currency": "EUR" },
    "MBCN": {"shortName": "Middlefield Banc Corp.", "currency": "USD" },
    "MBIN": {"shortName": "Merchants Bancorp", "currency": "USD" },
    "MBK.WA": {"shortName": "MBANK", "currency": "PLN" },
    "MBWM": {"shortName": "Mercantile Bank Corporation", "currency": "USD" },
    "MCB": {"shortName": "Metropolitan Bank Holding Corp.", "currency": "USD" },
    "MCBC": {"shortName": "Macatawa Bank Corporation", "currency": "USD" },
    "MCBS": {"shortName": "MetroCity Bankshares, Inc.", "currency": "USD" },
    "MEGA.JK": {"shortName": "Bank Mega Tbk", "currency": "IDR" },
    "MFG": {"shortName": "Mizuho Financial Group, Inc. Sp", "currency": "USD" },
    "MLVF": {"shortName": "Malvern Bancorp, Inc.", "currency": "USD" },
    "MLYBY": {"shortName": "MALAYAN BANKING BERHAD SPONS AD", "currency": "USD" },
    "MNSB": {"shortName": "MainStreet Bancshares, Inc.", "currency": "USD" },
    "MOFG": {"shortName": "MidWestOne Financial Group, Inc", "currency": "USD" },
    "MONET.PR": {"shortName": "MONETA MONEY BANK", "currency": "CZK" },
    "MQG.AX": {"shortName": "MACQ GROUP FPO", "currency": "AUD" },
    "MS": {"shortName": "Morgan Stanley", "currency": "USD" },
    "MTB": {"shortName": "M&T Bank Corporation", "currency": "USD" },
    "MTPOF": {"shortName": "METROPOLITAN BANK & TRUST CO", "currency": "USD" },
    "MUFG": {"shortName": "Mitsubishi UFJ Financial Group,", "currency": "USD" },
    "MVBF": {"shortName": "MVB Financial Corp.", "currency": "USD" },
    "MYFW": {"shortName": "First Western Financial, Inc.", "currency": "USD" },
    "MZTF.TA": {"shortName": "MIZRAHI TEFAHOT", "currency": "ILS" },
    "NA.TO": {"shortName": "NATIONAL BANK OF CANADA", "currency": "CAD" },
    "NAB.AX": {"shortName": "NAT. BANK FPO", "currency": "AUD" },
    "NBHC": {"shortName": "National Bank Holdings Corporat", "currency": "USD" },
    "NBN": {"shortName": "Northeast Bank", "currency": "USD" },
    "NBTB": {"shortName": "NBT Bancorp Inc.", "currency": "USD" },
    "NDA-FI.HE": {"shortName": "Nordea Bank Abp", "currency": "EUR" },
    "NED.JO": {"shortName": "Nedbank Group Ltd", "currency": "ZAR" },
    "NFBK": {"shortName": "Northfield Bancorp, Inc.", "currency": "USD" },
    "NIC": {"shortName": "Nicolet Bankshares Inc.", "currency": "USD" },
    "NMR": {"shortName": "Nomura Holdings Inc", "currency": "USD" },
    "NRIM": {"shortName": "Northrim BanCorp Inc", "currency": "USD" },
    "NTB": {"shortName": "Bank of N.T. Butterfield & Son ", "currency": "USD" },
    "NU": {"shortName": "Nu Holdings Ltd.", "currency": "USD" },
    "NWBI": {"shortName": "Northwest Bancshares, Inc.", "currency": "USD" },
    "NWG": {"shortName": "NatWest Group plc", "currency": "USD" },
    "NYCB": {"shortName": "New York Community Bancorp, Inc", "currency": "USD" },
    "O39.SI": {"shortName": "OCBC Bank", "currency": "SGD" },
    "OBNK": {"shortName": "Origin Bancorp, Inc.", "currency": "USD" },
    "OBS.VI": {"shortName": "Oberbank AG", "currency": "EUR" },
    "OBT": {"shortName": "Orange County Bancorp, Inc.", "currency": "USD" },
    "OCFC": {"shortName": "OceanFirst Financial Corp.", "currency": "USD" },
    "OFG": {"shortName": "OFG Bancorp", "currency": "USD" },
    "OPOF": {"shortName": "Old Point Financial Corporation", "currency": "USD" },
    "OPY": {"shortName": "Oppenheimer Holdings, Inc.", "currency": "USD" },
    "ORRF": {"shortName": "Orrstown Financial Services Inc", "currency": "USD" },
    "OSBC": {"shortName": "Old Second Bancorp, Inc.", "currency": "USD" },
    "OTP.BD": {"shortName": "OTP BANK PLC", "currency": "HUF" },
    "OVBC": {"shortName": "Ohio Valley Banc Corp.", "currency": "USD" },
    "OZK": {"shortName": "Bank OZK", "currency": "USD" },
    "PACW": {"shortName": "PacWest Bancorp", "currency": "USD" },
    "PBB.DE": {"shortName": "DT PFANDBRIEFBK AG", "currency": "EUR" },
    "PDLB": {"shortName": "Ponce Financial Group, Inc.", "currency": "USD" },
    "PEBK": {"shortName": "Peoples Bancorp of North Caroli", "currency": "USD" },
    "PEBO": {"shortName": "Peoples Bancorp Inc.", "currency": "USD" },
    "PEO.WA": {"shortName": "PEKAO", "currency": "PLN" },
    "PFBC": {"shortName": "Preferred Bank", "currency": "USD" },
    "PFC": {"shortName": "Premier Financial Corp.", "currency": "USD" },
    "PFIS": {"shortName": "Peoples Financial Services Corp", "currency": "USD" },
    "PFS": {"shortName": "Provident Financial Services, I", "currency": "USD" },
    "PGC": {"shortName": "Peapack-Gladstone Financial Cor", "currency": "USD" },
    "PIPR": {"shortName": "Piper Sandler Companies", "currency": "USD" },
    "PKBK": {"shortName": "Parke Bancorp, Inc.", "currency": "USD" },
    "PKO.WA": {"shortName": "PKOBP", "currency": "PLN" },
    "PLBC": {"shortName": "Plumas Bancorp", "currency": "USD" },
    "PNB.NS": {"shortName": "PUNJAB NATL BANK", "currency": "INR" },
    "PNC": {"shortName": "PNC Financial Services Group, I", "currency": "USD" },
    "PNFP": {"shortName": "Pinnacle Financial Partners, In", "currency": "USD" },
    "POLI.TA": {"shortName": "POALIM", "currency": "ILS" },
    "PPBI": {"shortName": "Pacific Premier Bancorp Inc", "currency": "USD" },
    "PRK": {"shortName": "Park National Corporation", "currency": "USD" },
    "PROV": {"shortName": "Provident Financial Holdings, I", "currency": "USD" },
    "PSB.NS": {"shortName": "PUNJAB & SIND BANK", "currency": "INR" },
    "PTRS": {"shortName": "Partners Bancorp", "currency": "USD" },
    "PVBC": {"shortName": "Provident Bancorp, Inc.", "currency": "USD" },
    "PWOD": {"shortName": "Penns Woods Bancorp, Inc.", "currency": "USD" },
    "QCRH": {"shortName": "QCR Holdings, Inc.", "currency": "USD" },
    "QNBFB.IS": {"shortName": "QNB FINANSBANK", "currency": "TRY" },
    "RAW.F": {"shortName": "RAIFFEISEN BK INTL INH.", "currency": "EUR" },
    "RBB": {"shortName": "RBB Bancorp", "currency": "USD" },
    "RBCAA": {"shortName": "Republic Bancorp, Inc.", "currency": "USD" },
    "RBLBANK.NS": {"shortName": "RBL BANK LIMITED", "currency": "INR" },
    "RMBI": {"shortName": "Richmond Mutual Bancorporation,", "currency": "USD" },
    "RNST": {"shortName": "Renasant Corporation", "currency": "USD" },
    "RRBI": {"shortName": "Red River Bancshares, Inc.", "currency": "USD" },
    "RVSB": {"shortName": "Riverview Bancorp Inc", "currency": "USD" },
    "RY": {"shortName": "Royal Bank Of Canada", "currency": "USD" },
    "SAB.MC": {"shortName": "BANCO DE SABADELL", "currency": "EUR" },
    "SAL": {"shortName": "Salisbury Bancorp, Inc.", "currency": "USD" },
    "SAN": {"shortName": "Banco Santander, S.A. Sponsored", "currency": "USD" },
    "SASR": {"shortName": "Sandy Spring Bancorp, Inc.", "currency": "USD" },
    "SBCF": {"shortName": "Seacoast Banking Corporation of", "currency": "USD" },
    "SBIN.NS": {"shortName": "STATE BK OF INDIA", "currency": "INR" },
    "SBK.JO": {"shortName": "Standard Bank Group Ltd", "currency": "ZAR" },
    "SBNY": {"shortName": "Signature Bank", "currency": "USD" },
    "SBSI": {"shortName": "Southside Bancshares, Inc.", "currency": "USD" },
    "SBT": {"shortName": "Sterling Bancorp, Inc.", "currency": "USD" },
    "SCHW": {"shortName": "Charles Schwab Corporation (The", "currency": "USD" },
    "SEB-A.ST": {"shortName": "Skandinaviska Enskilda Banken s", "currency": "SEK" },
    "SFBS": {"shortName": "ServisFirst Bancshares, Inc.", "currency": "USD" },
    "SFNC": {"shortName": "Simmons First National Corporat", "currency": "USD" },
    "SFST": {"shortName": "Southern First Bancshares, Inc.", "currency": "USD" },
    "SGKN.SW": {"shortName": "ST GALLER KB N", "currency": "CHF" },
    "SHB-A.ST": {"shortName": "Svenska Handelsbanken ser. A", "currency": "SEK" },
    "SHBI": {"shortName": "Shore Bancshares Inc", "currency": "USD" },
    "SLM": {"shortName": "SLM Corporation", "currency": "USD" },
    "SMBC": {"shortName": "Southern Missouri Bancorp, Inc.", "currency": "USD" },
    "SMBK": {"shortName": "SmartFinancial, Inc.", "currency": "USD" },
    "SMFG": {"shortName": "Sumitomo Mitsui Financial Group", "currency": "USD" },
    "SNV": {"shortName": "Synovus Financial Corp.", "currency": "USD" },
    "SOUTHBANK.NS": {"shortName": "SOUTH INDIA BANK", "currency": "INR" },
    "SPL.WA": {"shortName": "SANPL", "currency": "PLN" },
    "SPOL.OL": {"shortName": "SPAREBANK 1 ØSTLANDET", "currency": "NOK" },
    "SRCE": {"shortName": "1st Source Corporation", "currency": "USD" },
    "SSB": {"shortName": "SouthState Corporation", "currency": "USD" },
    "SSBK": {"shortName": "Southern States Bancshares, Inc", "currency": "USD" },
    "STAN.L": {"shortName": "STANDARD CHARTERED PLC ORD USD0", "currency": "GBP" },
    "STBA": {"shortName": "S&T Bancorp, Inc.", "currency": "USD" },
    "STEL": {"shortName": "Stellar Bancorp, Inc.", "currency": "USD" },
    "STT": {"shortName": "State Street Corporation", "currency": "USD" },
    "SUN.AX": {"shortName": "SUNCORP FPO", "currency": "AUD" },
    "SUPV": {"shortName": "Grupo Supervielle S.A.", "currency": "USD" },
    "SWED-A.ST": {"shortName": "Swedbank AB ser A", "currency": "SEK" },
    "SYBT": {"shortName": "Stock Yards Bancorp, Inc.", "currency": "USD" },
    "TBBK": {"shortName": "The Bancorp, Inc.", "currency": "USD" },
    "TBNK": {"shortName": "Territorial Bancorp Inc.", "currency": "USD" },
    "TCBI": {"shortName": "Texas Capital Bancshares, Inc.", "currency": "USD" },
    "TCBK": {"shortName": "TriCo Bancshares", "currency": "USD" },
    "TCBX": {"shortName": "Third Coast Bancshares, Inc.", "currency": "USD" },
    "TCFC": {"shortName": "The Community Financial Corpora", "currency": "USD" },
    "TD": {"shortName": "Toronto Dominion Bank (The)", "currency": "USD" },
    "TFC": {"shortName": "Truist Financial Corporation", "currency": "USD" },
    "TFIN": {"shortName": "Triumph Financial, Inc.", "currency": "USD" },
    "TFSL": {"shortName": "TFS Financial Corporation", "currency": "USD" },
    "TMP": {"shortName": "Tompkins Financial Corporation", "currency": "USD" },
    "TOWN": {"shortName": "Towne Bank", "currency": "USD" },
    "TPEIR.AT": {"shortName": "PIRAEUS FINANCIAL HOLDINGS SA", "currency": "EUR" },
    "TRMK": {"shortName": "Trustmark Corporation", "currency": "USD" },
    "TRST": {"shortName": "TrustCo Bank Corp NY", "currency": "USD" },
    "TSBK": {"shortName": "Timberland Bancorp, Inc.", "currency": "USD" },
    "TTB.BK": {"shortName": "TTB_TMBTHANACHART BANK", "currency": "THB" },
    "U11.SI": {"shortName": "UOB", "currency": "SGD" },
    "UBS": {"shortName": "UBS Group AG Registered", "currency": "USD" },
    "UBSI": {"shortName": "United Bankshares, Inc.", "currency": "USD" },
    "UCBI": {"shortName": "United Community Banks, Inc.", "currency": "USD" },
    "UCG.MI": {"shortName": "UNICREDIT", "currency": "EUR" },
    "UMBF": {"shortName": "UMB Financial Corporation", "currency": "USD" },
    "UNB": {"shortName": "Union Bankshares, Inc.", "currency": "USD" },
    "UNI.MC": {"shortName": "UNICAJA BANCO, S.A.", "currency": "EUR" },
    "UNIONBANK.NS": {"shortName": "UNION BK OF INDIA", "currency": "INR" },
    "UNTY": {"shortName": "Unity Bancorp, Inc.", "currency": "USD" },
    "USB": {"shortName": "U.S. Bancorp", "currency": "USD" },
    "VABK": {"shortName": "Virginia National Bankshares Co", "currency": "USD" },
    "VAKBN.IS": {"shortName": "VAKIFLAR BANKASI", "currency": "TRY" },
    "VBNK": {"shortName": "VersaBank", "currency": "USD" },
    "VBTX": {"shortName": "Veritex Holdings, Inc.", "currency": "USD" },
    "VLK.AS": {"shortName": "V LANSCHOT KEMPEN", "currency": "EUR" },
    "VMUK.L": {"shortName": "VIRGIN MONEY UK PLC ORD GBP0.10", "currency": "GBP" },
    "WABC": {"shortName": "Westamerica Bancorporation", "currency": "USD" },
    "WAFD": {"shortName": "Washington Federal, Inc.", "currency": "USD" },
    "WAL": {"shortName": "Western Alliance Bancorporation", "currency": "USD" },
    "WASH": {"shortName": "Washington Trust Bancorp, Inc.", "currency": "USD" },
    "WBC.AX": {"shortName": "WESTPAC FPO", "currency": "AUD" },
    "WBS": {"shortName": "Webster Financial Corporation", "currency": "USD" },
    "WF": {"shortName": "Woori Financial Group Inc.", "currency": "USD" },
    "WFC": {"shortName": "Wells Fargo & Company", "currency": "USD" },
    "WMPN": {"shortName": "William Penn Bancorporation", "currency": "USD" },
    "WNEB": {"shortName": "Western New England Bancorp, In", "currency": "USD" },
    "WSBC": {"shortName": "WesBanco, Inc.", "currency": "USD" },
    "WSFS": {"shortName": "WSFS Financial Corporation", "currency": "USD" },
    "WTFC": {"shortName": "Wintrust Financial Corporation", "currency": "USD" },
    "YESBANK.NS": {"shortName": "YES BANK", "currency": "INR" },
    "YKBNK.IS": {"shortName": "YAPI VE KREDI BANK.", "currency": "TRY" },
    "ZION": {"shortName": "Zions Bancorporation N.A.", "currency": "USD" },
    "ZYE1.F": {"shortName": "ADDIKO BANK AG INH.", "currency": "EUR" },
}



FIX_DATA = {
  "FIBI.TA":   [{"shares": 100_000_000,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  "600919.SS": [{"shares": 15_520_000_000, "dateFormatted": dat,} for dat in QUARTER_DATES],
  "601211.SS": [{"shares": 7_510_000_000,  "dateFormatted": dat,} for dat in QUARTER_DATES],
  "601939.SS": [{"shares": 9_590_000_000,  "dateFormatted": dat,} for dat in QUARTER_DATES],
  "601658.SS": [{"shares": 79_300_000_000, "dateFormatted": dat,} for dat in QUARTER_DATES],
  "BSLI3.SA":  [{"shares": 280_150_000,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  "D05.SI":    [{"shares": 280_150_000,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  "MB.MI":     [{"shares": 840_690_000,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  "ISP.MI":    [{"shares": 18_260_000_000, "dateFormatted": dat,} for dat in QUARTER_DATES],
  "BMED.MI":   [{"shares": 738_850_000,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  "UCG.MI":    [{"shares": 1_820_000_000,  "dateFormatted": dat,} for dat in QUARTER_DATES],
  "BAMI.MI":   [{"shares": 1_510_000_000,  "dateFormatted": dat,} for dat in QUARTER_DATES],
  "SBK.JO":    [{"shares": 1_650_000_000,  "dateFormatted": dat,} for dat in QUARTER_DATES],
  "NED.JO":    [{"shares": 485_250_000,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  "FSR.JO":    [{"shares": 5_610_000_000,  "dateFormatted": dat,} for dat in QUARTER_DATES],
  "CPI.JO":    [{"shares": 115_790_000,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  "DSY.JO":    [{"shares": 658_400_000,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  "7182.T":    [{"shares": 3_620_000_000,  "dateFormatted": dat,} for dat in QUARTER_DATES],
  "8308.T":    [{"shares": 2_360_000_000,  "dateFormatted": dat,} for dat in QUARTER_DATES],
  "8421.T":    [{"shares": 708_220,        "dateFormatted": dat,} for dat in QUARTER_DATES],
  "8601.T":    [{"shares": 1_450_000_000,  "dateFormatted": dat,} for dat in QUARTER_DATES],
  "RAW.F":     [{"shares": 328_410_000,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  "EBO.F":     [{"shares": 406_930_000,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  "CIN.F":     [{"shares": 2_980_000_000,  "dateFormatted": dat,} for dat in QUARTER_DATES],
  "ZYE1.F":    [{"shares": 19_470_000,     "dateFormatted": dat,} for dat in QUARTER_DATES],
  "0B2.F":     [{"shares": 82_150_000,     "dateFormatted": dat,} for dat in QUARTER_DATES],
  # "BMRI.JK":   [{"shares": 93_330_000_000, "dateFormatted": dat,} for dat in QUARTER_DATES],
  # "BNLI.JK":   [{"shares": 26_880_000,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  # "ISCTR.IS":  [{"shares": 0,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  # "KLNMA.IS":  [{"shares": 0,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  # "QNBFB.IS":  [{"shares": 0,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  "MONET.PR":  [{"shares": 511_000_000,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  "KOMB.PR":   [{"shares": 511_000_000,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  "OTP.BD":    [{"shares": 278_890_000,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  "SPL.WA":    [{"shares": 102_190_000,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  "TTB.BK":    [{"shares": 96_870_000_000, "dateFormatted": dat,} for dat in QUARTER_DATES],
  "DANS.VI":   [{"shares": 858_320_000,    "dateFormatted": dat,} for dat in QUARTER_DATES],
  "U11.SI":    [{"shares": 1_680_000_000,  "dateFormatted": dat,} for dat in QUARTER_DATES],
}




